CREATE DATABASE IF NOT EXISTS appliance_recycle DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE appliance_recycle;

CREATE TABLE IF NOT EXISTS residents (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    phone VARCHAR(20) NOT NULL UNIQUE COMMENT '手机号',
    password VARCHAR(255) NOT NULL COMMENT '密码（哈希）',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_phone (phone)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='居民用户表';

CREATE TABLE IF NOT EXISTS admins (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE COMMENT '管理员用户名',
    password VARCHAR(255) NOT NULL COMMENT '密码（哈希）',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='管理员表';

CREATE TABLE IF NOT EXISTS appliance_types (
    id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE COMMENT '家电类型名称',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='家电类型表';

INSERT INTO appliance_types (name) VALUES
    ('冰箱'), ('洗衣机'), ('空调'), ('电视机'), ('电脑'),
    ('热水器'), ('微波炉'), ('油烟机'), ('燃气灶'), ('其他')
ON DUPLICATE KEY UPDATE name=name;

CREATE TABLE IF NOT EXISTS time_slots (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    slot_date DATE NOT NULL COMMENT '排班日期',
    start_time TIME NOT NULL COMMENT '开始时间',
    end_time TIME NOT NULL COMMENT '结束时间',
    capacity INT UNSIGNED NOT NULL DEFAULT 10 COMMENT '容量上限',
    booked_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '已预约数',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_slot (slot_date, start_time, end_time),
    INDEX idx_slot_date (slot_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='排班时段表';

CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    order_no VARCHAR(32) NOT NULL UNIQUE COMMENT '预约单号',
    resident_id BIGINT UNSIGNED NOT NULL COMMENT '居民ID',
    slot_id BIGINT UNSIGNED NOT NULL COMMENT '时段ID',
    phone VARCHAR(20) NOT NULL COMMENT '联系手机',
    address VARCHAR(255) NOT NULL COMMENT '上门地址',
    appliance_type_id TINYINT UNSIGNED NOT NULL COMMENT '家电类型ID',
    appliance_weight DECIMAL(8,2) NOT NULL COMMENT '家电重量（kg）',
    status TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '状态：1待上门 2已完成 3已取消',
    remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_resident (resident_id),
    INDEX idx_slot (slot_id),
    INDEX idx_status (status),
    INDEX idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='预约表';
